server:
  port: 10005

spring:
  application:
    name: chat-memory-demo
  profiles:
    active: local
  ai:
    openai:
      api-key: ${API_KEY}
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: Qwen/Qwen3-8B
    memory:
      redis:
        host: ${REDIS_HOST}
        port: 6379
        # 没有设置password则无需填写
        password: ${REDIS_PASSWORD}
        timeout: 4000
    chat:
      memory:
        repository:
          jdbc:
            mysql:
              jdbc-url: ${MYSQL_JDBC_URL}?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&tinyInt1isBit=false&allowLoadLocalInfile=true&allowLocalInfile=true&allowUrl
              username: ${MYSQL_USERNAME}
              password: ${MYSQL_PASSWORD}
              enabled: true
              driver-class-name: com.mysql.cj.jdbc.Driver

# NOTE: 在使用数据库时，无需自己建表