server:
  port: 10002

spring:
  application:
    name: alibaba-chat-demo
  ai:
    dashscope:
      api-key: ${API_KEY}
  profiles:
    active: default

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG